### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by Ownasaurus** [Ownasaurus/TASLink#13]
TASLink> load smbsmw.tcf
Now preparing TASLink....
Traceback (most recent call last):
  File "TASLink.py", line 745, in <module>
    send_frames(run_index, latches)
  File "TASLink.py", line 97, in send_frames
    ser.write(''.join(inputBuffers[index][framecount:(framecount + amount)]))
IndexError: list index out of range
Run has been successfully loaded!
TASLink> exit

This occurred after doing a few loads, removes, and resets.  Need to find bug and fix.

**Comment by Ownasaurus** [comment]
Potential fix being pushed right now; closing unless issue reappears again
